name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - name: Fork Sync
        uses: tgymnich/fork-sync@v1.2.1
        with:
          base: master
          head: master
